openapi: 3.0.0
info:
  title: Draft API
  version: 1.0.0
paths:
  /draft:
    get:
      summary: Get an list of draft object
      parameters:
        - name: userId
          in: query
          schema:
            type: string
      responses:
        '200':
          description: The list of draft object
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Draft'
  /draft/{id}:
    get:
      summary: Get an draft object by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: The Draft Object
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Draft'
    put:
      summary: Get an draft object by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: The Draft Object
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Draft'
components:
  schemas:
    DraftLink:
      type: object
      properties:
        id:
          type: string
        version:
          type: integer
        initVersion:
          type: integer
        objectId:
          type: string
    Draft:
      type: object
      properties:
        id:
          type: string
        type:
          type: string
        version:
          type: integer
        parentId:
          type: string
        userId:
          type: string
        content:
          type: object
    Item:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        description:
          type: string
